[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
command = "cd /app && PYTHONPATH=/app python -m src.main"
