services:
  - type: web
    name: edubot1
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: BLOGGER_ID
        sync: false
